[tool.black]
line-length = 88
target-version = ["py37"]

[tool.pyright]
reportGeneralTypeIssues = "information"
pythonVersion = "3.7"
include = ["mnamer"]
exclude = ["playground.py", "venv"]
venv = ["venv"]

[tool.isort]
profile = "black"
py_version = 37
line_length = 88
known_first_party = "mnamer"
combine_star = true
combine_straight_imports = false
overwrite_in_place = true
