[project]
name = "mnamer"
description = "A command-line utility for organizing media files."
authors = [{ name = "Jessy Williams", email = "jessy@jessywilliams.com" }]
maintainers = [{ name = "Jessy Williams", email = "jessy@jessywilliams.com" }]
license = { file = "LICENSE.txt" }
requires-python = ">=3.8"
dynamic = ["version", "readme", "dependencies", "optional-dependencies"]
scripts = { mnamer = "mnamer.__main__:main" }
urls = { repository = "https://github.com/jkwill87/mnamer" }

[tool.setuptools]
packages = ["mnamer"]

[tool.setuptools.package-data]
"*" = ["LICENSE.txt", "README.md", "py.typed"]

[tool.setuptools.dynamic]
version = { attr = "mnamer.__version__.VERSION" }
readme = { file = ["README.md"] }
dependencies = { file = "requirements.txt" }

[tool.setuptools.dynamic.optional-dependencies]
dev = { file = "requirements-dev.txt" }
test = { file = "requirements-test.txt" }

[build-system]
requires = ["setuptools >= 61.0.0", "wheel"]
build-backend = "setuptools.build_meta"

[tool.black]
line-length = 88
target-version = ["py38"]

[tool.pyright]
reportGeneralTypeIssues = "information"
pythonVersion = "3.8"
include = ["mnamer"]
exclude = ["playground.py", "venv"]
venv = ["venv"]

[tool.isort]
profile = "black"
py_version = 38
line_length = 88
known_first_party = "mnamer"
combine_star = true
combine_straight_imports = false
overwrite_in_place = true

[tool.pylint.messages_control]
max-line-length = 88
disable = ["C0103", "C0114", "C0116", "C0209", "E0401", "R0801"]

[tool.mypy]
incremental = false
python_version = "3.8"
