name: push

on:
  push:
  schedule:
    - cron: "0 8 * * 1" # Mondays at 8am

jobs:
  black: # --------------------------------------------------------------------
    runs-on: ubuntu-latest

    steps:
      - name: Checking out Git Commit
        uses: actions/checkout@v2

      - name: Installing Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Installing Black from PyPI
        run: pip install -q black

      - name: Verifying Codebase is Formatted using Black
        run: black --check .

  test: # ---------------------------------------------------------------------
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.x"]
    name: test-v${{matrix.python-version}}

    steps:
      - name: Checking out Git Commit
        uses: actions/checkout@v2

      - name: Installing Python 3
        uses: actions/setup-python@v2
        with:
          python-version: ${{matrix.python-version}}

      - name: Installing Requirements
        run: pip install -q -U pip -r requirements-test.txt

      - name: Running Local Unit Tests
        run: >-
          python -m pytest
          -m local
          --durations=10
          --cov=./
          --cov-append
          --cov-report=term-missing
          --cov-report=xml

      - name: Running Network Unit Tests
        run: >-
          python -m pytest
          -m network
          --reruns 3
          --durations=10
          --cov=./
          --cov-append
          --cov-report=term-missing
          --cov-report=xml

      - name: Running End to End Tests
        run: >-
          python -m pytest
          -m e2e
          --reruns 3
          --durations=10
          --cov=./
          --cov-append
          --cov-report=term-missing
          --cov-report=xml

      - name: Reporting Coverage Statistics
        if: >
          success()
          && github.event_name == 'push'
          && github.ref == 'refs/heads/master'
          && matrix['python-version'] == '3.x'
        uses: codecov/codecov-action@v1

  publish: # ---------------------------------------------------------------------
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags')

    steps:
      - name: Checking out Git Commit
        uses: actions/checkout@v2

      - name: Installing Python 3
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Installing Requirements
        run: pip install -q -U pip -r requirements.txt twine

      - name: Building universal wheel
        run: python setup.py sdist bdist_wheel --universal

      - name: Uploading to PyPI
        run: >-
          twine upload
          --username jkwill87
          --password ${{secrets.pypi_password}}
          dist/*
